
# tap repositories and their packages

tap homebrew/core
brew fish
brew gdbm
brew git
brew libyaml
brew mas
brew openssl
brew pcre2
brew perl
brew python
brew readline
brew reattach-to-user-namespace
brew ruby
brew sqlite
brew tree
brew vim

tap caskroom/cask
cask slack
cask freemind
cask sketch
cask atom
cask mi
cask android-sdk
cask franz
cask firefox
cask google-chrome
cask alfred
cask skitch

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 443987910 1Password (6.8.6)
appstore 406056744 Evernote (6.13.1)
appstore 682658836 GarageBand (10.2.0)
appstore 408981434 iMovie (10.1.8)
appstore 409183694 Keynote (7.3.1)
appstore 539883307 LINE (5.5.1)
appstore 1295203466 Microsoft Remote Desktop (10.1.3)
appstore 715768417 Microsoft Remote Desktop (8.0.27325)
appstore 409203825 Numbers (4.3.1)
appstore 409201541 Pages (6.3.1)
